### ISSUE TITLE
[BUG] Vectorization and index analyzer bug for more complicated tensor expressions

### ISSUE THREAD

**Issue by campsd** [yhtang/FunFact#142]
**Describe the bug**
The `vectorize` method throws `SyntaxError: Incorrect number of indices. Expects 4, got 3.` in the index analyzer pass for certain complicated tensor expressions.

**To Reproduce**
Steps or a code snippet to reproduce the behavior:
```python
from funfact.vectorization import vectorize
tsrex = ((ff.eye(2) & ff.eye(2)) + (ff.eye(2) & ff.eye(2)))
tsrex = tsrex & ff.eye(2)
tsrex_vec = vectorize(tsrex, 3)
```
The tensor expression on the second line can be correctly vectorized, adding the term on the 3rd line introduces the error.

**Comment by yhtang** [comment]
I'll look into that.

**Comment by yhtang** [comment]
I'm rewriting many components of `lang`, so that we will have two levels of representations: a `SourcePrimitive` which corresponds to what users input, and an `IntermediatePrimitive` (i.e. IR) that dispatches the source primitives based on semantics. Vectorization will then happen at the IR level, thus eliminating many ambiguities in the source representation.
