### ISSUE TITLE
Support penalty terms on leaf tensors

### ISSUE THREAD

**Issue by campsd** [yhtang/FunFact#143]
It would be good to have a mechanism to enforce penalties on the leaf tensors that are summed together with the loss when optimizing a tensor expression. A great example use case is a penalty on the unitariness of the leaf matrices in a quantum circuit, another similar example is if we want to optimize a matrix factorization with constraints on the leafs (e.g SVD, NNMF, QR)

It seems to me that the most straightforward way to add this feature is to let the user add a penalty term upon initialization:

An API somewhat like this:
```python
Q = ff.tensor(4, 4, initiazer=unitary_init, penalty=is_unitary)
R = ff.tensor(4, 2, penalty=is_upper_triangular)
tsrex = Q @ R
# ...
fac = ff.factorize(tsrex, target, penalty_weights=0.1) # optimize QR factorization of 4x2 matrix, penalty_weights can be the hyper parameter for the loss function.
```

I think this is more user-friendly and easier to add to FunFact (can we just use the payload mechanism?) compared to setting the penalties when calling the algorithm:

`factorize(tsrex, target, penalties={is_unitary: Q, is_upper_triangular: R})`

Because after some interpreter passes it might be harder to match the tensors in this case?

**Comment by yhtang** [comment]
This sounds like a really good idea! I just want to note that there is a key difference between adding the penalty as an attribute of the abstract tensor and using the payload mechanism. This is because the abstract tensors are themselves attributes of the `_ASNode`s, so they are equivalent to a payload.

Given that the same abstract tensor may show up in multiple nodes in a tensor expression, it is probably better to have the penalty be part of the abstract tensor specification.

Another nit-pick is that I find it a bit weird to say 'this tensor has a unitary penalty term', whose actual meaning is probably 'this tensor has a unitary constraint'. That said, I'm not 100% sure what'll be the best name for this new property that we will add. :smile:
